export const assetPaths = {
  images: {
    background: 'assets/images/background.webp',
    confetti: 'assets/images/confetti.webp',
    exportIcon: 'assets/images/export-icon.svg',
    failIcon: 'assets/images/fail_icon.webp',
    footerBar: 'assets/images/footer-bar.webp',
    phoneDisplayBox: 'assets/images/phone-display-box.svg',
    prizeJerseyArgentina: 'assets/images/prize-jersey-argentina.webp',
    prizeKyats: 'assets/images/prize-kyats.webp',
    prizePedestal: 'assets/images/prize-pedestal.webp',
    prizeTv360Jersey: 'assets/images/prize-tv360-jersey.webp',
    qrCode: 'assets/images/qr-code.webp',
    selectWinnerBtn: 'assets/images/select-winner-btn.svg',
    selectedArrow: 'assets/images/selected-arrow.svg',
    subTagEng: 'assets/images/sub-tag-eng.webp',
    tagline: 'assets/images/tagline.webp',
    tv360Logo: 'assets/images/tv360-logo.webp',
    uploadIcon: 'assets/images/upload-icon.svg',
    wcLogo: 'assets/images/wc-logo.webp',
    wcPackages: 'assets/images/wc-packages.webp',
    winnersTag: 'assets/images/winnerstag.webp',
  },
} as const
